labels:
  env: dev

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    # <-- Change with your forked URL -->
    repoURL: https://github.com/lolucodes/eks-blueprints-workloads
    targetRevision: main
  ingress:
    host: dev.example.com

  # Thoses default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: eks-blueprint-cluster # the name of EKS cluster
  blueprint: 'terraform' # cdk | terraform
  karpenterInstanceProfile:
  ingress:
    type: 'alb' # nginx | alb
    host: # empty or your domain like dev.example.com
